### ISSUE TITLE
INPUT - Map generating

### ISSUE THREAD

**Issue by jessyefuster** [jessyefuster/n-puzzle#3]
See #2 to get map characteristics

Add argument handling to the generating program

**Comment by jessyefuster** [comment]
0450ff9a93e5a7d0527fcb84a5091815e58a6026

**Comment by jessyefuster** [comment]
#873c11c94c1c05583cb5fb0eff74ccbaddccd74b

**Comment by jessyefuster** [comment]
873c11c94c1c05583cb5fb0eff74ccbaddccd74b

**Comment by jessyefuster** [comment]
cd82927

**Comment by jessyefuster** [comment]
f632263

**Comment by jessyefuster** [comment]
6ccd62a

**Comment by jessyefuster** [comment]
0450ff9

**Comment by jessyefuster** [comment]
f6ba498

**Comment by qjacob** [comment]
@jessyefuster create unittest in new branch and create a new issue for that. 
I want a minimum of 2 test, I let you guess what is this two test ;)
